name: Test

on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup gcloud
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} 
        project_id: ${{ secrets.GCP_PROJECT_ID }} 

    - name: Configure docker for GCP
      run: gcloud auth configure-docker

    - name: Build docker image
      run:  docker build -t europe-west4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sample-web-app/web-app:latest . 

    - name: Push to Google Artifact Registry
      run:  docker push europe-west4-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/sample-web-app/web-app:latest
